# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 03:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stblog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='stArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Title', max_length=32)),
                ('content', models.TextField(null=True)),
                ('pup_time', models.DateTimeField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
